import { useEffect, useMemo, useState } from 'react'
import { Album, BookOpen, Copy, Grid2X2, ImagePlus, Library, ListFilter, MoreHorizontal, Pencil, Plus, Search, Tag, Trash2, X } from 'lucide-react'
import type { Collection, LibraryData, LibraryItem, MediaType, SearchItem } from './types'

const seed: LibraryData = { collections: [
  { id: 'favorites', name: 'All-time favorites', description: 'The ones I keep returning to.', createdAt: Date.now() - 3 },
  { id: 'weekends', name: 'Slow weekends', description: 'A quiet stack for unhurried days.', createdAt: Date.now() - 2 },
  { id: 'reference', name: 'Creative reference', description: 'Ideas worth keeping close.', createdAt: Date.now() - 1 }
], items: [] }
const demo: LibraryItem[] = [
  { id:'d1',sourceId:'demo1',type:'album',title:'Blue Train',creator:'John Coltrane',year:'1958',image:'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/d1/5d/9c/d15d9c2d-d9d0-a3c4-938b-74d81c7517c6/00602537694908.rgb.jpg/600x600bb.jpg',description:'A landmark hard bop recording.',externalUrl:'',collectionId:'favorites',tags:['Jazz','Hard bop'],addedAt:1},
  { id:'d2',sourceId:'demo2',type:'book',title:'The Left Hand of Darkness',creator:'Ursula K. Le Guin',year:'1969',image:'https://covers.openlibrary.org/b/isbn/9780441478125-L.jpg',description:'A groundbreaking work of speculative fiction.',externalUrl:'',collectionId:'favorites',tags:['Science fiction'],addedAt:2},
  { id:'d3',sourceId:'demo3',type:'album',title:'Carrie & Lowell',creator:'Sufjan Stevens',year:'2015',image:'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/17/c4/7f/17c47f45-721c-0dbf-ddf2-4c693d71750c/656605609668.jpg/600x600bb.jpg',description:'An intimate folk record.',externalUrl:'',collectionId:'weekends',tags:['Folk','Indie'],addedAt:3}
]

const uid = () => crypto.randomUUID()
const saveFallback = (data: LibraryData) => localStorage.setItem('shelf-sound', JSON.stringify(data))
async function loadData(): Promise<LibraryData> {
  if (window.libraryAPI) { const d = await window.libraryAPI.read(); return d.collections?.length ? d : { ...seed, items: demo } }
  const d = localStorage.getItem('shelf-sound'); return d ? JSON.parse(d) : { ...seed, items: demo }
}

export default function App() {
  const [data,setData] = useState<LibraryData>(seed), [ready,setReady]=useState(false)
  const [active,setActive]=useState('all'), [view,setView]=useState<'library'|'search'>('library')
  const [query,setQuery]=useState(''), [kind,setKind]=useState<MediaType>('book'), [results,setResults]=useState<SearchItem[]>([])
  const [loading,setLoading]=useState(false), [newOpen,setNewOpen]=useState(false), [newName,setNewName]=useState('')
  const [resultPage,setResultPage]=useState(1), [hasMoreResults,setHasMoreResults]=useState(false)
  const [searchError,setSearchError]=useState('')
  const [selected,setSelected]=useState<SearchItem|null>(null), [tagging,setTagging]=useState<LibraryItem|null>(null), [tagText,setTagText]=useState('')
  const [editingCollection,setEditingCollection]=useState<Collection|null>(null), [collectionTag,setCollectionTag]=useState('')
  const [confirmingDelete,setConfirmingDelete]=useState(false)
  const [filter,setFilter]=useState('all')

  useEffect(()=>{ loadData().then(d=>{setData(d);setReady(true)}) },[])
  const persist=(next:LibraryData)=>{ setData(next); if(window.libraryAPI) window.libraryAPI.write(next); else saveFallback(next) }
  const items=useMemo(()=>data.items.filter(i=>(active==='all'||i.collectionId===active)&&(filter==='all'||i.type===filter)),[data,active,filter])
  const tags=useMemo(()=>Array.from(new Set([...data.items.flatMap(i=>i.tags),...data.collections.flatMap(c=>c.tags||[])])),[data])

  async function loadResultPage(page:number){ if(!query.trim())return;setLoading(true);setSearchError('');setResults([]);const size=12
    try { if(kind==='book') { const start=(page-1)*size;const fields='key,title,author_name,first_publish_year,cover_i,subject,isbn,edition_count';const j=window.libraryAPI?await window.libraryAPI.searchBooks(query,page,size):await fetch(`https://openlibrary.org/search.json?q=${encodeURIComponent(query)}&page=${page}&limit=${size}&fields=${fields}`).then(r=>r.json());const found=j.docs||[];setResults(found.map((x:any)=>({sourceId:x.key||String(x.cover_i||x.title),type:'book',title:x.title||'Untitled',creator:(x.author_name||['Unknown author']).join(', '),year:String(x.first_publish_year||''),image:x.cover_i?`https://covers.openlibrary.org/b/id/${x.cover_i}-L.jpg`:'',description:(x.subject||[]).slice(0,4).join(' · ')||`${x.edition_count||1} known edition${x.edition_count===1?'':'s'}`,externalUrl:x.key?`https://openlibrary.org${x.key}`:''})));setHasMoreResults(start+found.length<(j.num_found||0)) }
      else { const offset=(page-1)*size;const term=query.replaceAll('"','');const searchQuery=`primarytype:album AND (artist:"${term}" OR releasegroup:"${term}")`;const j=window.libraryAPI?await window.libraryAPI.searchMusic(query,page,size):await fetch(`https://musicbrainz.org/ws/2/release-group/?query=${encodeURIComponent(searchQuery)}&fmt=json&limit=${size}&offset=${offset}`).then(r=>r.json());const found=(j['release-groups']||[]).filter((x:any)=>x['primary-type']==='Album');setResults(found.map((x:any)=>{const styles=[x['primary-type'],...(x['secondary-types']||[]),...(x.genres||[]).slice(0,2).map((g:any)=>g.name)].filter(Boolean);return {sourceId:x.id,type:'album',title:x.title||'Untitled release',creator:(x['artist-credit']||[]).map((a:any)=>a.name).join(', ')||'Unknown artist',year:(x['first-release-date']||'').slice(0,4),image:`https://coverartarchive.org/release-group/${x.id}/front-500`,description:styles.join(' · ')||'Album',externalUrl:`https://musicbrainz.org/release-group/${x.id}`}}));setHasMoreResults(offset+(j['release-groups']||[]).length<(j.count||j['release-group-count']||0)) }
      setResultPage(page)
    } catch {setResults([]);setHasMoreResults(false);setSearchError('The catalog could not be reached. Check your internet connection and try again.')} finally {setLoading(false)}
  }
  function search(e:React.FormEvent){e.preventDefault();loadResultPage(1)}
  function addCollection(e:React.FormEvent){e.preventDefault();if(!newName.trim())return;const c:Collection={id:uid(),name:newName.trim(),description:'A new corner of your library.',notes:'',tags:[],createdAt:Date.now()};persist({...data,collections:[...data.collections,c]});setNewName('');setNewOpen(false);setActive('all')}
  function addItem(item:SearchItem,collectionId:string){ if(data.items.some(i=>i.sourceId===item.sourceId&&i.collectionId===collectionId)){setSelected(null);return};persist({...data,items:[...data.items,{...item,id:uid(),collectionId,tags:[],addedAt:Date.now()}]});setSelected(null) }
  function removeItem(id:string){persist({...data,items:data.items.filter(i=>i.id!==id)});setTagging(null)}
  function addTag(){if(!tagging||!tagText.trim())return;const t=tagText.trim();persist({...data,items:data.items.map(i=>i.id===tagging.id?{...i,tags:Array.from(new Set([...i.tags,t]))}:i)});setTagging({...tagging,tags:Array.from(new Set([...tagging.tags,t]))});setTagText('')}
  function removeTag(t:string){if(!tagging)return;persist({...data,items:data.items.map(i=>i.id===tagging.id?{...i,tags:i.tags.filter(x=>x!==t)}:i)});setTagging({...tagging,tags:tagging.tags.filter(x=>x!==t)})}
  function saveCollection(e:React.FormEvent){e.preventDefault();if(!editingCollection)return;persist({...data,collections:data.collections.map(c=>c.id===editingCollection.id?editingCollection:c)});setEditingCollection(null);setCollectionTag('')}
  function addCollectionTag(){if(!editingCollection||!collectionTag.trim())return;setEditingCollection({...editingCollection,tags:Array.from(new Set([...(editingCollection.tags||[]),collectionTag.trim()]))});setCollectionTag('')}
  function loadCover(file?:File){if(!file||!editingCollection)return;const reader=new FileReader();reader.onload=()=>setEditingCollection(current=>current?{...current,cover:String(reader.result)}:current);reader.readAsDataURL(file)}
  function copyCollection(){if(!editingCollection)return;const newId=uid();const copy:Collection={...editingCollection,id:newId,name:`${editingCollection.name} copy`,createdAt:Date.now(),tags:[...(editingCollection.tags||[])]};const copiedItems=data.items.filter(i=>i.collectionId===editingCollection.id).map(i=>({...i,id:uid(),collectionId:newId,tags:[...i.tags],addedAt:Date.now()}));persist({collections:[...data.collections,copy],items:[...data.items,...copiedItems]});setEditingCollection(null);setActive('all')}
  function deleteCollection(){if(!editingCollection)return;persist({collections:data.collections.filter(c=>c.id!==editingCollection.id),items:data.items.filter(i=>i.collectionId!==editingCollection.id)});setEditingCollection(null);setConfirmingDelete(false);setActive('all')}
  const activeName=active==='all'?'My library':data.collections.find(c=>c.id===active)?.name||'Collection'
  if(!ready)return <div className="loading-page">Opening your library…</div>
  return <div className="app-shell">
    <aside>
      <div className="brand"><span className="brand-mark"><img src="./logo.png" alt=""/></span><b>Shelf & Sound</b></div>
      <button className={`nav-main ${active==='all'&&view==='library'?'active':''}`} onClick={()=>{setActive('all');setView('library')}}><Library/>My library<span>{data.items.length}</span></button>
      <div className="section-label"><span>Collections</span><button aria-label="New collection" onClick={()=>setNewOpen(true)}><Plus/></button></div>
      <nav>{data.collections.map(c=><button key={c.id} className={active===c.id&&view==='library'?'active':''} onClick={()=>{setActive(c.id);setView('library')}}><span className="dot"/>{c.name}<small>{data.items.filter(i=>i.collectionId===c.id).length}</small></button>)}</nav>
      <div className="tag-cloud"><div className="section-label"><span>Tags</span></div>{tags.slice(0,8).map(t=><button key={t} onClick={()=>{setActive('all');setView('library')}}><Tag/> {t}</button>)}</div>
      <div className="aside-bottom"><p><b>{data.items.length}</b> pieces collected</p><div><span style={{width:`${Math.min(data.items.length*6,100)}%`}}/></div></div>
    </aside>
    <main>
      <header><div><p className="eyebrow">YOUR PERSONAL ARCHIVE</p><h1>{view==='search'?'Discover something new':activeName}</h1></div><button className="discover" onClick={()=>{if(view==='search')setView('library');else if(active==='all')setNewOpen(true);else setView('search')}}>{view==='search'?<Library/>:active==='all'?<Plus/>:<Search/>}{view==='search'?'Back to library':active==='all'?'New collection':'Add to collection'}</button></header>
      {view==='search'?<section className="search-view">
        <div className="search-panel"><div className="type-toggle"><button className={kind==='book'?'on':''} onClick={()=>setKind('book')}><BookOpen/>Books</button><button className={kind==='album'?'on':''} onClick={()=>setKind('album')}><Album/>Albums</button></div><form onSubmit={search}><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={kind==='book'?'Search by title, author, or ISBN…':'Search by album or artist…'}/><button>Search</button></form><p>Searches live catalogs and brings the details back to your shelves.</p></div>
        <div className="results-heading"><h2>{loading?'Searching…':searchError?'Search unavailable':results.length?`${results.length} results`:'Try a search above'}</h2>{searchError&&<p className="search-error">{searchError}</p>}</div>
        <div className="result-grid">{results.map(r=>{const saved=data.items.filter(i=>i.sourceId===r.sourceId).length;return <article key={r.sourceId} className="result-card" onClick={()=>setSelected(r)}><Cover item={r}/><div><span className={`kind ${r.type}`}>{r.type}</span><h3>{r.title}</h3><p>{r.creator}</p><small>{saved?`Saved in ${saved} ${saved===1?'collection':'collections'}`:(r.year||'Year unknown')}</small></div><button className={saved?'saved':''} aria-label={saved?'Add to another collection':'Add'}>{saved?<span>✓</span>:<Plus/>}</button></article>})}</div>{(resultPage>1||hasMoreResults)&&<div className="pagination"><button disabled={loading||resultPage===1} onClick={()=>loadResultPage(resultPage-1)}>Previous</button><span>Page {resultPage}</span><button disabled={loading||!hasMoreResults} onClick={()=>loadResultPage(resultPage+1)}>Next results</button></div>}
      </section>:active==='all'?<section className="collection-home">
        <div className="home-intro"><p>{data.collections.length} {data.collections.length===1?'collection':'collections'} · {data.items.length} pieces</p><p>Your collections are the heart of your library. Open one to browse, or edit it to add a cover, notes, and tags.</p></div>
        {data.collections.length?<div className="collection-grid">{data.collections.map(c=>{const collectionItems=data.items.filter(i=>i.collectionId===c.id);const fallback=collectionItems.find(i=>i.image)?.image;return <article className="collection-card" key={c.id} onClick={()=>setActive(c.id)}><div className="collection-cover">{c.cover||fallback?<img src={c.cover||fallback} alt=""/>:<div><BookOpen/><Album/></div>}<span>{collectionItems.length} {collectionItems.length===1?'piece':'pieces'}</span><button aria-label={`Edit ${c.name}`} onClick={e=>{e.stopPropagation();setEditingCollection({...c,tags:c.tags||[],notes:c.notes||''})}}><Pencil/>Edit</button></div><div className="collection-copy"><h2>{c.name}</h2><p>{c.notes||c.description||'Add notes about this collection.'}</p><div className="collection-tags">{(c.tags||[]).map(t=><span key={t}><Tag/>{t}</span>)}</div></div></article>})}</div>:<div className="empty"><h2>Start your first collection</h2><p>Create a named home for books and albums you want to keep together.</p><button className="discover" onClick={()=>setNewOpen(true)}><Plus/>New collection</button></div>}
      </section>:<section className="library-view">
        <div className="toolbar"><div className="summary"><span>{items.length} {items.length===1?'piece':'pieces'}</span><i/> <span>{new Set(items.flatMap(i=>i.tags)).size} tags</span></div><div className="filters"><ListFilter/><button className={filter==='all'?'on':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='book'?'on':''} onClick={()=>setFilter('book')}>Books</button><button className={filter==='album'?'on':''} onClick={()=>setFilter('album')}>Albums</button><Grid2X2/></div></div>
        {items.length?<div className="shelf-grid">{items.map(i=><article className={`shelf-card ${i.type}`} key={i.id}><div className="cover-wrap"><Cover item={i}/><button className="more" onClick={()=>setTagging(i)} aria-label="Edit tags"><MoreHorizontal/></button></div><div className="card-copy"><span className={`kind ${i.type}`}>{i.type}</span><h3>{i.title}</h3><p>{i.creator} {i.year&&<><i/> {i.year}</>}</p><div className="chips">{i.tags.map(t=><span key={t}>{t}</span>)}<button onClick={()=>setTagging(i)}><Plus/> tag</button></div></div></article>)}</div>:<div className="empty"><div><BookOpen/><Album/></div><h2>This shelf is waiting</h2><p>Search the catalogs to add a book or album to this collection.</p><button className="discover" onClick={()=>setView('search')}><Search/>Discover items</button></div>}
      </section>}
    </main>
    {newOpen&&<Modal close={()=>setNewOpen(false)}><p className="eyebrow">NEW COLLECTION</p><h2>Make a new shelf</h2><form className="modal-form" onSubmit={addCollection}><label>Collection name<input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Late-night listening"/></label><div><button type="button" className="ghost" onClick={()=>setNewOpen(false)}>Cancel</button><button className="primary">Create collection</button></div></form></Modal>}
    {selected&&<Modal close={()=>setSelected(null)}><div className="add-preview"><Cover item={selected}/><div><span className={`kind ${selected.type}`}>{selected.type}</span><h2>{selected.title}</h2><p>{selected.creator} · {selected.year}</p></div></div><label className="select-label">Save to collection<div className="collection-options">{data.collections.map(c=><button key={c.id} onClick={()=>addItem(selected,c.id)}><span className="dot"/><span><b>{c.name}</b><small>{data.items.filter(i=>i.collectionId===c.id).length} items</small></span><Plus/></button>)}</div></label></Modal>}
    {tagging&&<Modal close={()=>setTagging(null)}><p className="eyebrow">ORGANIZE ITEM</p><h2>{tagging.title}</h2><p className="muted">Add genres, styles, moods, or any labels that help you find it later.</p><form className="tag-form" onSubmit={e=>{e.preventDefault();addTag()}}><input autoFocus value={tagText} onChange={e=>setTagText(e.target.value)} placeholder="e.g. Ambient"/><button className="primary">Add tag</button></form><div className="edit-tags">{tagging.tags.map(t=><span key={t}>{t}<button onClick={()=>removeTag(t)}><X/></button></span>)}</div><button className="delete" onClick={()=>removeItem(tagging.id)}><Trash2/>Remove from library</button></Modal>}
    {editingCollection&&<Modal close={()=>{setEditingCollection(null);setConfirmingDelete(false)}}>{confirmingDelete?<div className="delete-confirm"><Trash2/><p className="eyebrow">DELETE COLLECTION</p><h2>Delete {editingCollection.name}?</h2><p>This will also remove {data.items.filter(i=>i.collectionId===editingCollection.id).length} {data.items.filter(i=>i.collectionId===editingCollection.id).length===1?'item':'items'} in this collection. This cannot be undone.</p><div><button className="ghost" autoFocus onClick={()=>setConfirmingDelete(false)}>Keep collection</button><button className="danger-button" onClick={deleteCollection}>Delete permanently</button></div></div>:<><p className="eyebrow">COLLECTION DETAILS</p><h2>Edit {editingCollection.name}</h2><form className="collection-form" onSubmit={saveCollection}><label className="cover-upload"><div>{editingCollection.cover?<img src={editingCollection.cover} alt="Collection cover preview"/>:<ImagePlus/>}</div><span><b>Cover photo</b><small>Choose a JPG, PNG, or WebP image</small></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>loadCover(e.target.files?.[0])}/></label><label>Collection name<input value={editingCollection.name} onChange={e=>setEditingCollection({...editingCollection,name:e.target.value})}/></label><label>Notes<textarea rows={4} value={editingCollection.notes||''} onChange={e=>setEditingCollection({...editingCollection,notes:e.target.value})} placeholder="Why did you make this collection? What belongs here?"/></label><label>Tags<div className="inline-tag"><input value={collectionTag} onChange={e=>setCollectionTag(e.target.value)} placeholder="e.g. Summer" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addCollectionTag()}}}/><button type="button" onClick={addCollectionTag}>Add</button></div></label><div className="edit-tags">{(editingCollection.tags||[]).map(t=><span key={t}>{t}<button type="button" onClick={()=>setEditingCollection({...editingCollection,tags:(editingCollection.tags||[]).filter(x=>x!==t)})}><X/></button></span>)}</div><div className="collection-danger"><button type="button" onClick={copyCollection}><Copy/>Copy collection</button><button type="button" onClick={()=>setConfirmingDelete(true)}><Trash2/>Delete collection</button></div><div className="form-actions"><button type="button" className="ghost" onClick={()=>setEditingCollection(null)}>Cancel</button><button className="primary">Save changes</button></div></form></>}</Modal>}
  </div>
}

function Cover({item}:{item:{image:string;title:string;type:MediaType}}){return <div className={`cover ${item.type}`}>{item.image?<img src={item.image} alt=""/>:item.type==='book'?<BookOpen/>:<Album/>}</div>}
function Modal({children,close}:{children:any;close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="modal-close" onClick={close}><X/></button>{children}</div></div>}
